repositories:
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
    - name: incubator
      url: https://kubernetes-charts-incubator.storage.googleapis.com
    - name: bitnami
      url: https://charts.bitnami.com/bitnami

environments:
  default:

releases:
  - name: database
    namespace: workshop
    chart: stable/mysql
    createNamespace: true
    values:
      # use helm secrets plugin for non-workshop use cases
      # https://github.com/zendesk/helm-secrets
      - initializationFiles:
          wordpress.sql: |-
            CREATE DATABASE IF NOT EXISTS wordpress DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
            CREATE USER 'wordpress' IDENTIFIED BY 'secret';
            GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress';
            FLUSH PRIVILEGES;

  - name: wordpress
    namespace: workshop
    chart: bitnami/wordpress
    values:
      - mariadb:
          enabled: false
      - externalDatabase:
          host: "database-mysql" 
      - externalDatabase:
          database: "wordpress" 
      - externalDatabase:
          user: "wordpress"
      # use helm secrets plugin for non-workshop use cases
      # https://github.com/zendesk/helm-secrets
      - externalDatabase:
          password: "secret"
